### ISSUE TITLE
Coaches' notes

### ISSUE THREAD

**Issue by tcrasset** [JayeshItaliya86/nyc_trees_jayesh#1]
# Feedback

## Repo

- Name of the repo should be `nyc-trees`.
- README titles are there, but please fill them in with correct information, check [here](https://github.com/becodeorg/GNT-Arai-2.31/blob/master/content/1.terminal/02.Git/5.Writing-A-Good-Readme.md). I don't really need much more than [this](https://github.com/tcrasset/hangman).

- For further projects, with more packages and so that you can have exact versions, have a look at `pip freeze` of `conda export`, to create a `requirements.txt` or a `environment.yml` file. More info [here](https://coderefinery.github.io/reproducible-research/03-dependencies/)

## Code

- Nice idea to copy the dataframe

- When creating a list (or dictionnary of renaming) of many items, order them vertically so we can easily read them.

  ```python

  columns_list =[
      'created_at',
      'tree_id',
      'block_id',
      'the_geom',
      'tree_dbh',
      'stump_diam',
      'curb_loc',
      'status',
      'health',
      ...
  ]

  # Above is more readable than below

  columns_list =['created_at','tree_id','block_id','the_geom','tree_dbh','stump_diam','curb_loc','status','health',
              'spc_latin','spc_common',
              'steward','guards','sidewalk','user_type','problems','root_stone','root_grate','root_other','trnk_wire',
              'trnk_light','trnk_other','brnch_ligh','brnch_shoe','brnch_othe','address','zipcode','zip_city','cb_num',
              'borocode','boroname','cncldist','st_assem','st_senate','nta','nta_name','boro_ct','state','latitude',
              'longitude','x_sp','y_sp']
  ```

- Good conversion to datetime
- Nice use of `applymap`
- Nice function, but you can use `map` for that.

  ```python
  def change_classification(data):
  if data == 'Yes':
  return 1
  elif data == 'No':
  return 0
  ```

- Could have had a list of columns and applied it to all of them directly, instead of doing the following

  ```python
  df['root_stone'] = df['root_stone'].apply(lambda data: change_classification(data))
  df['root_grate'] = df['root_grate'].apply(lambda data: change_classification(data))
  df['root_other'] = df['root_other'].apply(lambda data: change_classification(data))
  df['trunk_wire'] = df['trunk_wire'].apply(lambda data: change_classification(data))
  df['trunk_light'] = df['trunk_light'].apply(lambda data: change_classification(data))
  df['trunk_other'] = df['trunk_other'].apply(lambda data: change_classification(data))
  df['branch_light'] = df['branch_light'].apply(lambda data: change_classification(data))
  df['branch_sneakers'] = df['branch_sneakers'].apply(lambda data: change_classification(data))
  df['branch_other'] = df['branch_other'].apply(lambda data: change_classification(data))
  ```

- Nice use of `index=False` in `df.to_csv()`

**Comment by JayeshItaliya86** [comment]
Hi Tom,

Thanks for your feedback.
I gone through all and I would try to apply in my feature assignments.

Thanks,
Jayesh Italiya
